changed all the scripts to provide a consistent environment to the package scripts (basically, I rewrote everything, sorry)

diff --git a/opt/bin/shellpkg-update b/opt/bin/shellpkg-update
--- a/opt/bin/shellpkg-update
+++ b/opt/bin/shellpkg-update
@@ -1,14 +1,40 @@
-#!/bin/bash
+#!/bin/sh
 
-if [ "$*" == "" ]; then
-    echo "No package selected."
-    exit 1
+GENERAL_ERROR=1
+USAGE_ERROR=2
+PACKAGE_ERROR=3
+
+if [ -z "$1" ]; then
+    echo "No package specified."
+    echo "Usage: $0 <package name>"
+    exit $USAGE_ERROR
 fi
 
-echo "Package $1 selected for update:"
-#TODO: read metadata to check for new dependencies and conflicts
-read -n1 -p "Press any key to continue or hit ^c to abort."
-exec /opt/shellpkg-repo/$1/update.sh
-echo "Unknown package: $1"
-exit 1
+if [ -f /etc/shellpkg.conf ]; then
+    REPO=$(sed -ne '/^repo=/s/^repo=//p' /etc/shellpkg.conf)
+    # assume the user is not an idiot and don't do proper config validation
+else
+    echo "Config file not found!"
+    exit $GENERAL_ERROR
+fi
 
+if [ ! -d $REPO ]; then
+    echo "Repo directory not found: $REPO"
+    exit $GENERAL_ERROR
+fi
+
+if [ -d $REPO/$1 ]; then
+    echo "Package: $1"
+    echo "============"
+    #TODO: dependency and conflict checks
+    echo "============"
+    read -n1 -p "Press any key to continue with update or hit ^c to abort."
+    #TODO: handle dependencies and conflicts
+    cd /tmp
+    export BASE_DIR=$(sed -ne '/^base-directory=/s/^base-directory=//p' /etc/shellpkg.conf)
+    export PACKAGE_DIR=$REPO/$1
+    $PACKAGE_DIR/update.sh
+else
+    echo "Unknown package: $1"
+    exit $PACKAGE_ERROR
+fi
